version: '3.4'
services:
  ontop:
    image: ontop/ontop
    container_name: 'ontop'
    restart: unless-stopped
    network_mode: host
    env_file: .env
    environment:
      ONTOP_ONTOLOGY_FILE: /opt/ontop/input/omac.owl
      ONTOP_MAPPING_FILE: /opt/ontop/input/omac.obda
      ONTOP_PROPERTIES_FILE: /opt/ontop/input/vkg.docker.properties
      ONTOP_PORTAL_FILE: /opt/ontop/input/vkg.toml
      ONTOP_DB_URL: ${ONTOP_DB_URL} 
      ONTOP_DB_USER: ${ONTOP_DB_USER}
      ONTOP_DB_PASSWORD: ${ONTOP_DB_PASSWORD} 
      ONTOP_CORS_ALLOWED_ORIGINS: ${ONTOP_CORS_ALLOWED_ORIGINS}
    ports:
    - '18080:8080'
    volumes:
    - ./ontop/input:/opt/ontop/input
    - ./ontop/jdbc:/opt/ontop/jdbc
    entrypoint: [
      '/opt/ontop/entrypoint.sh',
      # '/opt/ontop/input/bin/wait-for-it.sh', 'localhost:5432', '--timeout=0', '--strict', '--',
      ]