title="Ontop Portal"

[[tabGroups]]

name="Example of SPARQL queries"

[[tabGroups.tabs]]

name="Person-works"
query="""
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dbp: <http://dbpedia.org/property/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX :<https://data.crimproject.org/>
PREFIX omac:<https://omac.crimproject.org/>

SELECT * WHERE {
  ?person a dbo:Person; dbp:name ?name; dbp:composer ?work.
  ?work dcterms:title ?workTitle; dbp:genre/omac:has_value :genre-mass.
}
"""