title="Ontop Portal"

[[tabGroups]]

name="Example of SPARQL queries"

[[tabGroups.tabs]]

name="Composers for masses"
query="""
prefix dbp: <http://dbpedia.org/property/>
prefix dcterms: <http://purl.org/dc/terms/>
prefix crdata: <https://data.crimproject.org/>
prefix omac: <https://omac.crimproject.org/>
PREFIX schema: <https://schema.org/>

SELECT *
{?composition a omac:MusicalExpression; 
      dcterms:title ?title;
      dbp:genre/omac:hasValue crdata:genre-mass;
               dbp:composer/schema:name ?composer_name. 

} order by ?composition

"""